### PR TITLE
Support single commands without termination character

### PR DESCRIPTION
**Pull request by jrviz**

### CODE REVIEW

**Comment by josephdadams** [comment]
If you draft a new release with the new version number before merging, when you merge it will auto generate new builds. 😃

**Comment by jrviz** [comment]
OK, I have done something wrong again ☹ I thought a build had kicked off but it still seems to be 1.0.10 in the images.

**Comment by josephdadams** [comment]
You have to create the new tag as well. I did it

**Comment by josephdadams** [comment]
Well they didn’t get uploaded because the release was already published

**Comment by josephdadams** [comment]
I’ll draft a 1.0.12 release and tag, then if you bump package JSON it will fire off the build automatically

**Pull request merged**
